package prototype.projects;

public enum Type {
    TRAVAUX_ROUTIERS,
    TRAVAUX_GAZ_ELECTRICITE,
    CONSTRUCTION_RENOVATION,
    ENTRETIEN_PAYSAGER,
    TRAVAUX_TRANSPORTS_COMMUN,
    TRAVAUX_SIGNALISATION_ECLAIRAGE,
    TRAVAUX_SOUTERRAINS,
    TRAVAIL_RESIDENTIEL,
    ENTRETIEN_URBAIN,
    ENTRETIEN_RESEAUX_TELECOMMUNICATION
}
